export const bangs = [
  { bang: "apkg", name: "Archlinux packages" },
  { bang: "archpkg", name: "Archlinux packages" },
  { bang: "arch", name: "Archlinux wiki" },
  { bang: "archwiki", name: "Archlinux wiki" },
  { bang: "archaur", name: "Archlinux AUR" },
  { bang: "aur", name: "Archlinux AUR" },
  { bang: "archlinux", name: "Archlinux Forum" },
  { bang: "archforum", name: "Archlinux Forum" },
  { bang: "w", name: "Wikipedia" },
  { bang: "wiki", name: "Wikipedia" },
  { bang: "bulba", name: "Bulbapedia" },
  { bang: "yt", name: "YouTube" },
  { bang: "youtube", name: "YouTube" },
  { bang: "ytor", name: "YouTube on Repeat" },
  { bang: "youtubeonrepeat", name: "YouTube on Repeat" },
  { bang: "gh", name: "Github" },
  { bang: "github", name: "Github" },
  { bang: "glab", name: "Gitlab" },
  { bang: "gitlab", name: "Gitlab" },
  { bang: "latexwb", name: "LaTeX Wikibooks" },
  { bang: "ctan", name: "CTAN" },
  { bang: "crates", name: "Crates.io" },
  { bang: "cargo", name: "Crates.io" },
  { bang: "rust", name: "Rust stdlib docs" },
  { bang: "rustdoc", name: "Rust docs" },
  { bang: "js", name: "MDN JS Documentation" },
  { bang: "css", name: "MDN CSS Documentation" },
  { bang: "csst", name: "CSS Tricks" },
  { bang: "r", name: "Reddit" },
  { bang: "subr", name: "Subreddits" },
  { bang: "subreddit", name: "Subreddits" },
  { bang: "dictionaryr", name: "Dictionary.com (reference)" },
  { bang: "thes", name: "Thesaurus.com" },
  { bang: "thesaurus", name: "Thesaurus.com" },
  { bang: "wa", name: "Wolfram Alpha" },
  { bang: "wolfram", name: "Wolfram Alpha" },
  { bang: "wolf", name: "Wolfram Alpha" },
  { bang: "math", name: "Wolfram Mathworld" },
  { bang: "mathworld", name: "Wolfram Mathworld" }
];
